### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by D042888-2** [SOSP-OS/android_device_amlogic_franklin#1]
Hello
Tell

denis@KOMP1:/media/denis/Build/SOSP-13_27.02.23$ make -j4 otapackage
22:38:53 ************************************************************
22:38:53 You are building on a machine with 15.6GB of RAM
22:38:53 
22:38:53 The minimum required amount of free memory is around 16GB,
22:38:53 and even with that, some configurations may not work.
22:38:53 
22:38:53 If you run into segfaults or other errors, try reducing your
22:38:53 -j value.
22:38:53 ************************************************************
build/make/core/soong_config.mk:213: warning: BOARD_PLAT_PUBLIC_SEPOLICY_DIR has
 been deprecated. Use SYSTEM_EXT_PUBLIC_SEPOLICY_DIRS instead.
build/make/core/soong_config.mk:214: warning: BOARD_PLAT_PRIVATE_SEPOLICY_DIR ha
s been deprecated. Use SYSTEM_EXT_PRIVATE_SEPOLICY_DIRS instead.
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=13
TARGET_PRODUCT=sosp_franklin
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_ARCH=arm
TARGET_ARCH_VARIANT=armv8-a
TARGET_CPU_VARIANT=generic
HOST_OS=linux
BUILD_ID=TQ1A.230205.002
OUT_DIR=/media/denis/Build/SOSP-13_27.02.23/out
PRODUCT_SOONG_NAMESPACES=device/amlogic/g12-common device/amlogic/common vendor/
amlogic/g12-common vendor/amlogic/franklin
============================================
[100% 398/398] analyzing Android.bp files and generating ninja file at /media/de
FAILED: /media/denis/Build/SOSP-13_27.02.23/out/soong/build.ninja
cd "$(dirname "/media/denis/Build/SOSP-13_27.02.23/out/host/linux-x86/bin/soong_
build")" && BUILDER="$PWD/$(basename "/media/denis/Build/SOSP-13_27.02.23/out/ho
st/linux-x86/bin/soong_build")" && cd / && env -i  "$BUILDER"     --top "$TOP"  
   --soong_out "/media/denis/Build/SOSP-13_27.02.23/out/soong"     --out "/media
/denis/Build/SOSP-13_27.02.23/out"     -o /media/denis/Build/SOSP-13_27.02.23/ou
t/soong/build.ninja --globListDir build --globFile /media/denis/Build/SOSP-13_27
.02.23/out/soong/globs-build.ninja -t -l /media/denis/Build/SOSP-13_27.02.23/out
/.module_paths/Android.bp.list --available_env /media/denis/Build/SOSP-13_27.02.
23/out/soong/soong.environment.available --used_env /media/denis/Build/SOSP-13_2
7.02.23/out/soong/soong.environment.used.build Android.bp
Killed
22:46:52 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.

#### failed to build some targets (11:47 (mm:ss)) ####

denis@KOMP1:/media/denis/Build/SOSP-13_27.02.23$

**Comment by Gnathvm** [comment]
Check your system config. Build it with at least 32GB Ram.
